name: Deploy to IIS

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore NuGet Packages
        run: |
          & "C:\actions-runner\nuget.exe" restore Contrack.sln

      - name: Build Solution
        run: |
          & "C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\MSBuild\Current\Bin\amd64\MSBuild.exe" Contrack.sln /p:Configuration=Release

      - name: Create Publish Folder
        run: |
          if (!(Test-Path "C:\temp\publish")) {
            New-Item -ItemType Directory -Path "C:\temp\publish"
          }

      - name: Clean Publish Folder
        run: |
          if (Test-Path "C:\temp\publish") {
            Remove-Item "C:\temp\publish\*" -Recurse -Force -ErrorAction SilentlyContinue
          }

      - name: Publish
        run: |
          & "C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\MSBuild\Current\Bin\amd64\MSBuild.exe" "Contrack\Contrack.csproj" /p:Configuration=Release /p:OutDir="C:\temp\publish\\"

      - name: Check Publish Output
        run: |
          echo "Checking publish folder..."
          dir "C:\temp\publish"

      - name: Deploy to IIS
        run: |
          if (!(Test-Path "C:\inetpub\wwwroot\contrack")) {
            New-Item -ItemType Directory -Path "C:\inetpub\wwwroot\contrack"
          }

          robocopy "C:\temp\publish" "C:\inetpub\wwwroot\contrack" /E /NFL /NDL /NJH /NJS /NC /NS

      - name: Check IIS Folder
        run: |
          echo "Checking IIS folder..."
          dir "C:\inetpub\wwwroot\contrack"