name: Deploy to IIS

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Build Solution
  run: |
    & "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" Contrack.sln /p:Configuration=Release

- name: Create Publish Folder
  run: |
    if (!(Test-Path "C:\temp\publish")) { New-Item -ItemType Directory -Path "C:\temp\publish" }

- name: Publish
  run: |
    & "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" Contrack.sln /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:publishUrl="C:\temp\publish"

      - name: Deploy to IIS
        run: |
          if exist "C:\inetpub\wwwroot\contrack" rmdir /s /q "C:\inetpub\wwwroot\contrack"
          mkdir "C:\inetpub\wwwroot\contrack"
          xcopy /E /Y /I "C:\temp\publish" "C:\inetpub\wwwroot\contrack"

      - name: Restart IIS
        run: iisreset