name: Deploy to IIS

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Restore NuGet Packages
        run: |
          & "C:\actions-runner\nuget.exe" restore Contrack.sln

      - name: Build Solution
        run: |
          & "C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\MSBuild\Current\Bin\amd64\MSBuild.exe" Contrack.sln /p:Configuration=Release

      - name: Create Publish Folder
        run: |
          if (!(Test-Path "C:\temp\publish")) {
            New-Item -ItemType Directory -Path "C:\temp\publish"
          }

      - name: Publish
        run: |
          & "C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\MSBuild\Current\Bin\amd64\MSBuild.exe" Contrack.sln /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:publishUrl="C:\temp\publish"

      - name: Deploy to IIS
        run: |
          if (!(Test-Path "C:\inetpub\wwwroot\contrack")) {
            New-Item -ItemType Directory -Path "C:\inetpub\wwwroot\contrack"
          }

          xcopy "C:\temp\publish\*" "C:\inetpub\wwwroot\contrack" /E /I /Y /C